let a = Number(prompt("Digite um número"))
let b = Number(prompt("Outro Número"))

console.log(`${a}+${b} = `+ (a + b))
console.log(`${a}-${b} = `+ (a - b))
console.log(`${b}-${a} = `+ (b - a))
console.log(`${a}x${b} = `+a * b)
console.log(`${a}/${b} = `+ (a / b).toFixed(2))
console.log(`${b}/${a} = `+ (b / a).toFixed(2))
console.log(`${a}^${b} = `+ a ** b)
console.log(`${b}^${a} = `+ b ** a)
console.log('√'+a+' = '+Math.sqrt(a).toFixed(2))
console.log('√'+b+' = '+Math.sqrt(b).toFixed(2))